ex1: main.o client.o
	gcc main.o client.o pattern-matching.o -o ex1

main.o: main.c client.h 
	gcc -Wall -c main.c -o main.o

client.o: client.c client.h
	gcc -Wall -c client.c -o client.o



clean:
	rm -rf *.o
