prog1: main.o student.o grade.o income.o
	gcc main.o student.o grade.o income.o -o prog1
	
main.o: main.c student.h
	gcc -c main.c -o main.o
	
student.o: student.c student.h
	gcc -c student.c -o student.o
	
grade.o: grade.c grade.h
	gcc -c grade.c -o grade.o
	
income.o: income.c income.h
	gcc -c income.c -o income.o
	
clean:
	rm -rf *.o